package checker

import (
	"strings"
)

// IsHTMLTagName returns true if the argument is a defined HTML5 tag, case
// insensitive.
//
// Note: In the interest of optimizing for the common case, the argument is
// assumed to be lowercase or uppercase. If `name` is mixed case, this function
// may return a false negative. Use IsHTMLTagNameSafe for a version that won't
// return a false negative.
//
func IsHTMLTagName(name string) bool {
	return tags[name]
}

// IsHTMLTagNameSafe returns true if the argument is a defined HTML5 tag. Unlike
// IsHTMLTagName, this version downcases the argument first to prevent mixed-
// case false negatives.
//
func IsHTMLTagNameSafe(name string) bool {
	return tags[strings.ToLower(name)]
}

// A sorted array of all HTML5 tags, stolen from
// https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/HTML5_element_list
var tags = map[string]bool{
	"a":          true,
	"abbr":       true,
	"address":    true,
	"area":       true,
	"article":    true,
	"aside":      true,
	"audio":      true,
	"b":          true,
	"base":       true,
	"bdi":        true,
	"bdo":        true,
	"blockquote": true,
	"body":       true,
	"br":         true,
	"button":     true,
	"canvas":     true,
	"caption":    true,
	"cite":       true,
	"code":       true,
	"col":        true,
	"colgroup":   true,
	"data":       true,
	"datalist":   true,
	"dd":         true,
	"del":        true,
	"details":    true,
	"dfn":        true,
	"div":        true,
	"dl":         true,
	"dt":         true,
	"em":         true,
	"embed":      true,
	"fieldset":   true,
	"figcaption": true,
	"figure":     true,
	"footer":     true,
	"form":       true,
	"h1":         true,
	"head":       true,
	"header":     true,
	"hr":         true,
	"html":       true,
	"i":          true,
	"iframe":     true,
	"img":        true,
	"input":      true,
	"ins":        true,
	"kbd":        true,
	"keygen":     true,
	"label":      true,
	"legend":     true,
	"li":         true,
	"link":       true,
	"main":       true,
	"map":        true,
	"mark":       true,
	"math":       true,
	"menu":       true,
	"menuitem":   true,
	"meta":       true,
	"meter":      true,
	"nav":        true,
	"noscript":   true,
	"object":     true,
	"ol":         true,
	"optgroup":   true,
	"option":     true,
	"output":     true,
	"p":          true,
	"param":      true,
	"pre":        true,
	"progress":   true,
	"q":          true,
	"rp":         true,
	"rt":         true,
	"ruby":       true,
	"s":          true,
	"samp":       true,
	"script":     true,
	"section":    true,
	"select":     true,
	"small":      true,
	"source":     true,
	"span":       true,
	"strong":     true,
	"style":      true,
	"sub":        true,
	"summary":    true,
	"svg":        true,
	"table":      true,
	"tbody":      true,
	"td":         true,
	"textarea":   true,
	"tfoot":      true,
	"th":         true,
	"thead":      true,
	"time":       true,
	"title":      true,
	"tr":         true,
	"track":      true,
	"u":          true,
	"ul":         true,
	"var":        true,
	"video":      true,
	"wbr":        true,
	"A":          true,
	"ABBR":       true,
	"ADDRESS":    true,
	"AREA":       true,
	"ARTICLE":    true,
	"ASIDE":      true,
	"AUDIO":      true,
	"B":          true,
	"BASE":       true,
	"BDI":        true,
	"BDO":        true,
	"BLOCKQUOTE": true,
	"BODY":       true,
	"BR":         true,
	"BUTTON":     true,
	"CANVAS":     true,
	"CAPTION":    true,
	"CITE":       true,
	"CODE":       true,
	"COL":        true,
	"COLGROUP":   true,
	"DATA":       true,
	"DATALIST":   true,
	"DD":         true,
	"DEL":        true,
	"DETAILS":    true,
	"DFN":        true,
	"DIV":        true,
	"DL":         true,
	"DT":         true,
	"EM":         true,
	"EMBED":      true,
	"FIELDSET":   true,
	"FIGCAPTION": true,
	"FIGURE":     true,
	"FOOTER":     true,
	"FORM":       true,
	"H1":         true,
	"HEAD":       true,
	"HEADER":     true,
	"HR":         true,
	"HTML":       true,
	"I":          true,
	"IFRAME":     true,
	"IMG":        true,
	"INPUT":      true,
	"INS":        true,
	"KBD":        true,
	"KEYGEN":     true,
	"LABEL":      true,
	"LEGEND":     true,
	"LI":         true,
	"LINK":       true,
	"MAIN":       true,
	"MAP":        true,
	"MARK":       true,
	"MATH":       true,
	"MENU":       true,
	"MENUITEM":   true,
	"META":       true,
	"METER":      true,
	"NAV":        true,
	"NOSCRIPT":   true,
	"OBJECT":     true,
	"OL":         true,
	"OPTGROUP":   true,
	"OPTION":     true,
	"OUTPUT":     true,
	"P":          true,
	"PARAM":      true,
	"PRE":        true,
	"PROGRESS":   true,
	"Q":          true,
	"RP":         true,
	"RT":         true,
	"RUBY":       true,
	"S":          true,
	"SAMP":       true,
	"SCRIPT":     true,
	"SECTION":    true,
	"SELECT":     true,
	"SMALL":      true,
	"SOURCE":     true,
	"SPAN":       true,
	"STRONG":     true,
	"STYLE":      true,
	"SUB":        true,
	"SUMMARY":    true,
	"SVG":        true,
	"TABLE":      true,
	"TBODY":      true,
	"TD":         true,
	"TEXTAREA":   true,
	"TFOOT":      true,
	"TH":         true,
	"THEAD":      true,
	"TIME":       true,
	"TITLE":      true,
	"TR":         true,
	"TRACK":      true,
	"U":          true,
	"UL":         true,
	"VAR":        true,
	"VIDEO":      true,
	"WBR":        true,
}
